version: '3.3'
services:
  panel:
    depends_on:
      cache:
        condition: service_started
      mysql:
        condition: service_started
    env_file: ./conf.d/panel.env
    image: ccarney16/pterodactyl-panel:latest
    ports:
      - 81:80
      - 444:443
    environment:
      - VIRTUAL_HOST=autiboymc.ddns.net
      - LETSENCRYPT_HOST=autiboymc.ddns.net
      - LETSENCRYPT_EMAIL=autiboystech@gmail.com
    restart: always
    volumes:
      - ./data/panel:/data
      - ./conf.d/letsencrypt:/etc/letsencrypt
      - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
      - ./conf.d/certs:/etc/certs
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.panel-reload.schedule: "${PANEL_RELOAD_SCHEDULE:-0 15 0 * * *}"
      ofelia.job-exec.panel-reload.command: "nginx -s reload"
  worker:
    command: wait-for -t 5 panel:80 -- php /var/www/html/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3
    depends_on:
      panel:
        condition: service_started
    env_file: ./conf.d/panel.env
    image: ccarney16/pterodactyl-panel:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.pqueue.schedule: "@every 1m"
      ofelia.job-exec.pqueue.command: "php /var/www/html/artisan schedule:run"
      ofelia.job-exec.pqueue.user: "nginx"
    restart: always
    volumes_from:
      - panel
  cron:
    command: daemon --docker
    depends_on:
      panel:
        condition: service_started
      worker:
        condition: service_started
      certbot:
        condition: service_started
      daemon:
        condition: service_started
    image: mcuadros/ofelia:latest
    network_mode: none
    privileged: true
    restart: always
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.le-renew.schedule: "0 0 0 * * *"
      ofelia.job-run.le-renew.container: pterodactyl_certbot_1
  cache:
    cpu_count: 2
    cpu_percent: 50
    image: redis:alpine
    mem_limit: 128m
    restart: always
  daemon:
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: ccarney16/pterodactyl-daemon:latest
    ports:
      - 2022:2022
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.20.0.100
    privileged: true
    restart: always
    volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}:${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
      - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - ./conf.d/daemon:/etc/pterodactyl
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d/certs:/etc/certs:ro
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.daemon-reload.schedule: "${DAEMON_RELOAD_SCHEDULE:-0 30 0 * * *}"
      ofelia.job-exec.daemon-reload.command: "kill -15 1"
  certbot:
    command: renew
    depends_on:
      panel:
        condition: service_started
    image: certbot/certbot:latest
    volumes_from:
      - panel
  mysql:
    image: mariadb:10.4
    env_file: ./conf.d/mariadb.env
    ports:
      - ${MYSQL_ADDRESS:-3306}
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16 
