debug: false
app_name: Pterodactyl
uuid: 445ca86c-9763-4f81-af3b-59f301aa0424
token_id: uYt8Cz3YK8hd4DyG
token: IOccSr27BtAEzddrdWbfs3Yjj64g5yMKWdqw2zf9p2u79Xu86lkQNx70RIbvgnPu
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/208.87.131.173/fullchain.pem
    key: /etc/letsencrypt/live/208.87.131.173/privkey.pem
  disable_remote_download: false
  upload_limit: 100
system:
  root_directory: /var/lib/pterodactyl
  log_directory: /var/log/pterodactyl
  data: /var/lib/pterodactyl/volumes
  archive_directory: /var/lib/pterodactyl/archives
  backup_directory: /var/lib/pterodactyl/backups
  username: pterodactyl
  timezone: UTC
  user:
    uid: 100
    gid: 101
  disk_check_interval: 150
  check_permissions_on_boot: true
  enable_log_rotate: true
  websocket_log_count: 150
  sftp:
    bind_address: 0.0.0.0
    bind_port: 2022
    read_only: false
  crash_detection:
    detect_clean_exit_as_crash: true
    timeout: 60
  backups:
    write_limit: 0
  transfers:
    download_limit: 0
docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
throttles:
  enabled: true
  lines: 2000
  maximum_trigger_count: 5
  line_reset_interval: 100
  decay_interval: 10000
  stop_grace_period: 15
remote: http://208.87.131.173:81
remote_query:
  timeout: 30
  boot_servers_per_page: 50
allowed_mounts: []
allowed_origins: []
